config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  post "/covers/accept", to: "covers#accept"


  root to: 'pages#home'
  resources :posts do
    resources :comments
  end

  resources :covers
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :body, presence: true
end

app/models/cover.rb
class Cover < ApplicationRecord
  belongs_to :user, optional: true
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments, dependent: :destroy
  belongs_to :user

  validates :title, presence: true
  validates :position, presence: true
  validates :store_name, presence: true
  validates :story, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :joe_code, presence: true
  has_one_attached :photo
  has_many :posts
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :joe_code, :photo])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :joe_code, :photo])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:create]
  def create
    @comment = Comment.new(comment_params)
    @post = Post.find(params[:post_id])
    @comment.post = @post

    @comment.user = current_user

    if @comment.save
      redirect_to post_path(@post)
    end
  end

  private
  
  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/covers_controller.rb
require 'json'
require 'open-uri'

class CoversController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show, :new, :create, :accept, :edit, :update, :destroy]
  
  def index
    @covers = Cover.all.order("created_at DESC")
    api_call
  end

  def show
    @cover = Cover.find(params[:id])
  end

  def accept
    Rails.logger.info "Accepted the shift #{current_user}"

    cover = Cover.find(params[:id])
    cover.user = current_user

    cover.save!
    redirect_to covers_path
  end

  def new
    @cover = Cover.new
  end

  def create
    @cover = Cover.create(cover_params)

    if @cover.save!
      redirect_to covers_path
    end
  end

  def api_call
    url = 'https://api.openweathermap.org/data/2.5/find?q=London&appid='
    user_serialized = URI.open(url).read
    opened_api = JSON.parse(user_serialized)
  end

  private

  def cover_params
    params.require(:cover).permit(:store_name, :date_of_shift, :time_of_shift, :descrption)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home, :team]
  def home
  end

  def team
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show, :new, :create, :edit, :update, :destroy]

  def index
    @posts = Post.all.order("created_at DESC")
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user

    if @post.save
      redirect_to posts_path
    else
      render 'new'
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])

    if @post.update(post_params)
      redirect_to posts_path
    else
      render 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    redirect_to posts_path
  end

  private

  def post_params
    params.require(:post).permit(:title, :position, :store_name, :story)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/covers/index.html.erb
<div class="container">
  <h1>Covers</h1>
    <div class="index-box-page">
      <% @covers.each do |cover| %>
        <%= cover.store_name %> <br>
        <%= cover.date_of_shift %> <br>
        <%= cover.time_of_shift %> <br>
        <%= cover.descrption %> <br>
          

          <form action="covers/accept" method="POST">
            <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
            <input type="hidden" name="id" value="<%= cover.id %>">
            <input class="btn btn-primary" type="submit" value="Accept">
          </form>

          <% if !cover.user.nil? %>
            <h6><%= cover.user.first_name %> <%= cover.user.last_name %> (<b>#<%= cover.user.joe_code %></b>)</h6>
          <% end %>
        <hr>
      <% end %>
    </div>
</div>

app/views/covers/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-12 col-sm-4">
      <div class="form-login">
        <%= simple_form_for @cover do |f| %>
          <%= f.input :store_name %>
          <%= f.input :date_of_shift %>
          <%= f.input :time_of_shift %>
          <%= f.input :descrption %>
          <%= f.button :submit, class: "btn btn-primary" %>
        <% end %>
     </div>
    </div>
  </div>
</div>

app/views/covers/show.html.erb
<%= @cover.store_name %> <br>
<%= @cover.date_of_shift %> <br>
<%= @cover.time_of_shift %> <br>
<%= @cover.descrption %>

<% if !@cover.user.nil? %>
  <%= @cover.user.first_name %>
<% end %>
<form action="accept" method="POST">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="hidden" name="id" value="<%= @cover.id %>"><br>
  <input type="submit" value="Accept">
</form>

app/views/layouts/_footer.html.erb
<div class="footer">
  <div style="margin-left: 55px;" class="footer-links">
    <a href="https://www.joejuice.com/" target="_blank"><i class="fas fa-home"></i></a>
    <a href="https://www.instagram.com/joeandthejuice/?hl=en" target="_blank"><i class="fab fa-instagram"></i></a>
    <a href="https://www.facebook.com/joeandthejuice/" target="_blank"><i class="fab fa-facebook"></i></a>
  </div>
  <div style="margin-right: 65px;" class="footer-copyright">
    This website is made by some cool guy at Tower42 <i class="fas fa-power-off"></i>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container">
      <h2><%= link_to "JOEBOOK", root_path, class: "joebook" %></h2>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>


    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav">
        <li class="nav-item active">
          <% if user_signed_in? %>
            <li><%= link_to "Create a Post", new_post_path, class: "nav-link link-text-home" %></li>
            <li><%= link_to "Create a Cover", new_cover_path, class: "nav-link link-text-home" %></li>
            <li><%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: "nav-link link-text-home" %></li>
          <% end %>
          <% if !user_signed_in? %>
            <li><%= link_to "Log In", new_user_session_path, class: "nav-link link-text-home" %></li>
            <li><%= link_to "Sign Up", new_user_registration_path, class: "nav-link link-text-home" %></li>
          <% end %>
        </li>
        <li class="nav-item dropdown">
          <div id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <% if user_signed_in? %>
              <% if current_user.photo.attached? %>
                <%= cl_image_tag current_user.photo.key, crop: :fill, class: 'avatar dropdown-toggle' %>
              <% else %>
                <%= image_tag("https://cphimageprocessor-prod.azurewebsites.net/merchants/merchant-1e87e9ba-4bed-4dad-8f91-e586ea04c65e.png", class: 'avatar dropdown-toggle' ) %>
              <% end %>
            <% end %>
          </div>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Account Settings", edit_user_registration_path, class: "dropdown-item" %>
          </div>
        </li>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JOEBOOKApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
  
    <%= render "layouts/navbar" %>

    <%= yield %>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= render "layouts/footer" %>

  </body>
</html>

app/views/pages/home.html.erb
<div style="background-image: linear-gradient(rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.5)), url(https://www.liverpool-one.com/wp-content/uploads/2016/10/joe-and-the-juice.jpg)" class="banner">
  <div class="container">
    <h1>Share your stories <strong>with people across</strong> the <strong>world wide web</strong>!</h1>
    <p>Sign up and start sharing your stories with us!</p>
      <%= link_to "Stories", posts_path, class: "btn  btn-flat" %>
      <%= link_to "Covers", covers_path, class: "btn  btn-flat", style: "margin-left: 5px;" %>
  </div>
</div>

<div class="container">

  <div class="home-page-card">
    <strong><h1>Share your story!</h1></strong>
    
    <p style="font-size: 17px;">
      When I started working at JOE, I realised that it's not your ordinary everyday workplace. 
      I was busy at the sandwich station and a guy out of nowhere hit the lamps and shouted vibes! I then immediately realised that I am out of my comfort zone. 
      The next thing I noticed is that everyone I spoke to had some crazy story about JOE or working at JOE and how fun the JOE parties are. 
      So that got me thinking, let me use my coding skills and build a website where people from JOE can share their stories and past experiences.
    </p>

    <p style="font-size: 17px;">
      I here present you JOEBOOK, a website/app where you can share your stories and past experiences
      as well as comment on them and see what people think about your story. You can also do other things like add profile
      pictures, add your JOE code so people can know how long you have been at JOE and add which store you work in.
    </p>

    <p style="font-size: 17px;">
      With this website/app I am currently working on a couple of new features such as a store covers page where the BM
      can post if he/she will need a cover for their store. As an employee, you can post if you would 
      like to pick up any shifts in certain stores. I am doing this so you don't have to go onto Facebook 
      and have a look there, which might be time-consuming.
    </p>

  </div>

    <div class="sign-container">
      <div class="sign">
        <span class="fast-flicker">T</span>ow<span class="flicker">e</span>r42
      </div>
    </div>

    <div class="home-page-border">
      <%# <%= image_tag "tower.jpg", class: 'heloo' %> %>
    </div>

</div>

app/views/posts/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-12 col-sm-4">
      <div class="form-login">
        <%= simple_form_for @post do |f| %>
          <%= f.input :title %>
          <%= f.input :position %>
          <%= f.input :store_name %>
          <%= f.input :story %>
          <%= f.button :submit, class: "btn btn-primary" %>
        <% end %>
     </div>
    </div>
  </div>
</div>

app/views/posts/edit.html.erb
<%= render  "posts/form" %>

app/views/posts/index.html.erb
<div class="container">
  <h1 style="margin-top:20px; font-weight: bold;">Post feed</h1>
  <% @posts.each do |post| %>
    <div class="index-box-page">
      <h2><%= post.title %></h2>
      <h5 style="font-weight: lighter;"><i><%= post.store_name %> || <%= post.user.first_name.capitalize %> <%= post.user.last_name.capitalize %>(<strong>#<%= post.user.joe_code %></strong>) || <%= post.position %></i></h5>
      <p><%= truncate(post.story, :length => 250) %> <%= link_to "see more", post_path(post) %></p>
    </div>
  <% end %>
</div>

app/views/posts/new.html.erb
<%= render  "posts/form" %>

app/views/posts/show.html.erb
<div class="container">
  <div class="index-box-page">
    <h1><%= @post.title %></h1>
    <h5 style="font-weight: lighter;"><i><%= @post.store_name %> || <%= @post.user.first_name.capitalize %> <%= @post.user.last_name.capitalize %>(#<strong><%= @post.user.joe_code %></strong>) || <%= @post.position %></i></h5>
    <p><%= @post.story %></p>
    
    <% if user_signed_in? %>
      <% if @post.user_id == current_user.id %>
        <%= link_to "Back", posts_path, class: "btn btn-primary" %><%= link_to "Edit", edit_post_path(@post), class: 'btn btn-info' %><%= link_to "Delete", post_path(@post), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger" %>
      <% end %>
    <% end %>
  </div>

  <div class="comment-show-boxes">
    <%= simple_form_for [@post, Comment.new] do |f| %>
      <%= f.input :body, label: "Comment" %>
      <%= f.button :submit, class: "btn btn-primary" %>
    <% end %>
  </div>

  <% if @post.comments.count == 0 %>
    <div class="index-box-page">
      <h3>Be the first to comment</h3>
    </div>
  <% else %>
    <h2 style="margin-top: 30px;"><strong>Comment Section</strong></h2>
    <div class="index-box-page">
      <% @post.comments.order("created_at DESC").each do |comment| %>
        <div class="name-boxes">
          <% if comment.user.photo.attached? %>
            <%= cl_image_tag comment.user.photo.key, crop: :fill, class: "avatar" %>
          <% else %>
            <%= image_tag("https://cphimageprocessor-prod.azurewebsites.net/merchants/merchant-1e87e9ba-4bed-4dad-8f91-e586ea04c65e.png", class: "avatar") %>
          <% end %>
          <div class="name-margins">
            <% if @post.user_id == comment.user_id %>
              <div style="margin-top: -10px;">
                <h5><%= comment.user.first_name.capitalize %> <%= comment.user.last_name.capitalize %> (<strong>#<%= comment.user.joe_code %>)</strong></h5>
                <h6 style="font-weight: lighter; margin-bottom: -10px;"><i>Author of this post</i></h6>
              </div>
            <% else %>
              <h5><%= comment.user.first_name.capitalize %> <%= comment.user.last_name.capitalize %> (<strong>#<%= comment.user.joe_code %>)</strong></h5>
            <% end %>
          </div>
        </div>

        <h6 style="font-weight: lighter;"><i>posted <%= time_ago_in_words(comment.created_at) %> ago</i></h6>
        <h4><%= comment.body %></h4>
        <hr>
      <% end %>
    </div>
  <% end %>
</div>